apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

patches:
- target:
    kind: ServiceMonitor
    name: ".*"
  patch: |-
    - op: add
      path: /metadata/labels/release
      value: prometheus