kind: Component
apiVersion: gikopsctl.config.k8s.io/v1alpha1
metadata:
  name: prometheus
  namespace: monitoring
  # disabled: true
helm:
  repo: prometheus-community 
  repo-url: https://prometheus-community.github.io/helm-charts
  version: v69.4.1
  chart: prometheus-community/kube-prometheus-stack
  after:
    resolves:
    - crds/**/crd-*.yaml
files:
  crds: crds/crds
dependsOn:
  - core/traefik
