kind: Component
apiVersion: gikopsctl.config.k8s.io/v1alpha1
metadata:
  name: mkcert
  namespace: cert-manager
dependsOn:
  - core/cert-manager
files:
  skipCRDs: true
exec:
  before:
    - |
      kubectl create secret tls mkcert-ca-key-pair --dry-run=client --output=yaml \
      --key "$(mkcert -CAROOT)"/rootCA-key.pem \
      --cert "$(mkcert -CAROOT)"/rootCA.pem -n cert-manager > ../base/mkcert-ca.yaml