# .github/workflows/release.yaml
name: Release Workflow

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod tidy

      - name: Create GitHub Release
        run: make release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}